/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author L E N O V O
 */
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import control.controller;
import javax.swing.JLabel;

public class MainView extends javax.swing.JFrame {

    controller dc;
    public MainView() {
        initComponents();
        dc = new controller(this);
        dc.isitabel();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama_pelanggan = new javax.swing.JTextField();
        Paket = new javax.swing.JTextField();
        Jadwal = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        SimpanButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        Id_layanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, 480));

        jLabel1.setText("Nama Pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 145, 110, -1));

        jLabel2.setText("Paket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 188, 98, -1));

        jLabel3.setText("Jadwal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 234, 37, -1));

        Nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(Nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 142, 132, -1));
        getContentPane().add(Paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 185, 132, -1));
        getContentPane().add(Jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 231, 132, -1));

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 293, -1, -1));

        SimpanButton.setText("Simpan");
        getContentPane().add(SimpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 293, -1, -1));

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HapusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 293, -1, -1));

        Id_layanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_layananActionPerformed(evt);
            }
        });
        getContentPane().add(Id_layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 102, 132, -1));

        jLabel4.setText("ID_Pelanggan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 105, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\AKuliah\\Tugas Semester 4\\praktikum\\GroomingKcg\\GroomingKcg\\GroomingKcg\\test\\kucing.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_pelangganActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void Id_layananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_layananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_layananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField Id_layanan;
    private javax.swing.JTextField Jadwal;
    private javax.swing.JTextField Nama_pelanggan;
    private javax.swing.JTextField Paket;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JTable TableData;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public controller getDc() {
        return dc;
    }

    public void setDc(controller dc) {
        this.dc = dc;
    }

    public JTextField getId_layanan() {
        return Id_layanan;
    }

    public void setId_layanan(JTextField Id_layanan) {
        this.Id_layanan = Id_layanan;
    }
    
    
    public JButton getHapusButton() {
        return HapusButton;
    }

    public void setHapusButton(JButton HapusButton) {
        this.HapusButton = HapusButton;
    }

    public JTextField getJadwal() {
        return Jadwal;
    }

    public void setJadwal(JTextField Jadwal) {
        this.Jadwal = Jadwal;
    }

    public JTextField getNama_pelanggan() {
        return Nama_pelanggan;
    }

    public void setNama_pelanggan(JTextField Nama_pelanggan) {
        this.Nama_pelanggan = Nama_pelanggan;
    }

    public JTextField getPaket() {
        return Paket;
    }

    public void setPaket(JTextField Paket) {
        this.Paket = Paket;
    }

    public JButton getSimpanButton() {
        return SimpanButton;
    }

    public void setSimpanButton(JButton SimpanButton) {
        this.SimpanButton = SimpanButton;
    }

    public JTable getTableData() {
        return TableData;
    }

    public void setTableData(JTable TableData) {
        this.TableData = TableData;
    }

    public JButton getUpdateButton() {
        return UpdateButton;
    }

    public void setUpdateButton(JButton UpdateButton) {
        this.UpdateButton = UpdateButton;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

}
